### ISSUE TITLE
On the it displays the wrong flag for the german language

### ISSUE THREAD

**Issue by keroe** [Hackathon2020/CoronaHackathon2020#74] opened 2020-04-23 18:28 UTC
![DAE6D095-5A0A-42D3-AECA-3D3783FF8FFF](https://user-images.githubusercontent.com/28650400/80135775-fb8ffa80-85a0-11ea-82cb-d0efff8ed274.jpeg)

**Comment by cwecht** [comment] 2020-04-23 19:45
Fixed in  #65

**Comment by jobleier** [comment] 2020-04-23 19:50
Caused by non german browser language. Works fine if browser has default language german, displays wrong language (text, not flag) otherwise.

**Comment by cwecht** [comment] 2020-04-30 18:36
@keroe could you confirm, that this bug has been fixed?

**Closed as completed** 2020-04-30 18:35 UTC
Labels: bug
